### ISSUE TITLE
Forbedring af Node-RED git-flow ved flere samtidige udviklere

### ISSUE THREAD

**Issue by ghost** [KvalitetsIT/node-red-template#3]
```[tasklist]
### Tasks
- [ ] https://github.com/Randers-Kommune-Digitalisering/k8s-issues/issues/12
```

**Comment by ghost** [comment]
I branchen ➡️ https://github.com/Randers-Kommune-Digitalisering/node-red-template/tree/3-forbedring-af-node-red-git-flow-ved-flere-samtidige-udviklere gøres brug af contrib modulet:
https://flows.nodered.org/node/node-red-contrib-js-storage der splitter flows.json op i flere mindre .js filer for hver tab og hver node i flowet. Det gør merging af branches nemt og hurtigt i forhold til at skulle merge to kæmpestore, svært overskuelige flows.json når man forsøger at merge en branch ind i main f.eks.

**Comment by ghost** [comment]
@st-randers Vil du teste deher ændringer og om der er noget der breaker?

**Comment by ghost** [comment]
@bork91, skal Docker buildet ændres nu hvor kildekoden ikke længere er i en fil "flows.json" men istedet ligger i /node-red/flows_js/ mappen? Jeg gætter på at den skal kopieres ind i imaget for at det fungerer i kubernetes, hvor man ikke mounter /data ?

Jeg kan godt give det et forsøg hvis det bare er at rette stien til COPY kommandoen i Dockerfile, men hvis der er noget jeg ikke har tænkt på vil jeg gerne have dine øjne på før vi merger..

**Comment by bork91** [comment]
@jmk-randers det skulle blot være at ændre COPY i Dockerfilen. Så den kopier mappen flows_js over.

**Comment by ghost** [comment]
@bork91.

Perfekt.. jeg har rettet Dockerfile i [denne branch](https://github.com/Randers-Kommune-Digitalisering/node-red-template/tree/3-forbedring-af-node-red-git-flow-ved-flere-samtidige-udviklere) i node-red-template - jeg pusher og laver en pull request. 

Jeg kan ikke teste om byggede containers kan deployes manuelt med med Argo, de jeg ikke p.t. kan logge ind. 

Istedet for at være afhængige af en person og en manuel deployment procedure foreslår jeg at sætte en tag-baseret autodeployment op så det kørte lidt mere automatiskt. Jeg har lavet et [draft issue](https://github.com/orgs/Randers-Kommune-Digitalisering/projects/21/views/7?pane=issue&itemId=23811170) på det på k8s-issue trackeren.

**Comment by ghost** [comment]
Backportet til auto-tilskudsberegning-fodterapi i https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/66
